<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.mongoplus</groupId>
    <artifactId>mongo-plus-bom</artifactId>
    <packaging>pom</packaging>
    <name>mongo-plus-bom</name>
    <version>2.2.0</version>
    <description>mongo-plus-bom</description>
    <url>https://www.mongoplus.com</url>
    <inceptionYear>2025</inceptionYear>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <scm>
        <connection>https://gitee.com/aizuda/mongo-plus.git</connection>
        <developerConnection>https://gitee.com/aizuda/mongo-plus.git</developerConnection>
        <url>https://gitee.com/aizuda/mongo-plus</url>
    </scm>

    <developers>
        <developer>
            <id>anwen</id>
            <name>anwen</name>
            <email>mongoplus.cn@gmail.com</email>
            <roles>
                <role>Project Manager</role>
                <role>Architect</role>
            </roles>
            <timezone>+8</timezone>
        </developer>
    </developers>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <mongoplus.version>2.2.0</mongoplus.version>
        <mongodb.version>5.4.0</mongodb.version>
        <central-publishing.version>0.6.0</central-publishing.version>
        <maven-release.version>2.5.3</maven-release.version>
        <maven-source.version>2.2.1</maven-source.version>
        <maven-gpg.version>1.5</maven-gpg.version>
        <javadoc.version>3.6.3</javadoc.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.mongoplus</groupId>
                <artifactId>mongo-plus-indexer</artifactId>
                <version>${mongoplus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mongoplus</groupId>
                <artifactId>mongo-plus-boot-starter</artifactId>
                <version>${mongoplus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mongoplus</groupId>
                <artifactId>mongo-plus-boot4-starter</artifactId>
                <version>${mongoplus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mongoplus</groupId>
                <artifactId>mongo-plus-core</artifactId>
                <version>${mongoplus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mongoplus</groupId>
                <artifactId>mongo-plus-sensitive-word</artifactId>
                <version>${mongoplus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mongoplus</groupId>
                <artifactId>mongo-plus-annotation</artifactId>
                <version>${mongoplus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mongoplus</groupId>
                <artifactId>mongo-plus-sharding</artifactId>
                <version>${mongoplus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mongoplus</groupId>
                <artifactId>mongo-plus-sharding-boot-starter</artifactId>
                <version>${mongoplus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mongoplus</groupId>
                <artifactId>mongo-plus-solon-plugin</artifactId>
                <version>${mongoplus.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>release</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <plugins>

                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <version>${central-publishing.version}</version>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>central</publishingServerId>
                        </configuration>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-release-plugin</artifactId>
                        <version>${maven-release.version}</version>
                        <extensions>true</extensions>
                        <configuration>
                            <autoVersionSubmodules>true</autoVersionSubmodules>
                            <useReleaseProfile>false</useReleaseProfile>
                            <releaseProfiles>release</releaseProfiles>
                            <goals>deploy</goals>
                        </configuration>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>${maven-source.version}</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>${javadoc.version}</version>
                    </plugin>

                    <!--<plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-gpg-plugin</artifactId>
                        <version>${maven-gpg.version}</version>
                        <executions>
                            <execution>
                                <id>sign-artifacts</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>-->

                </plugins>
            </build>
            <!-- maven中央仓库 -->
            <distributionManagement>
                <snapshotRepository>
                    <id>release</id>
                    <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
                </snapshotRepository>
                <repository>
                    <id>release</id>
                    <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
                </repository>
            </distributionManagement>
        </profile>

    </profiles>

</project>
